version: 0.2
env:
  variables:
    ARTIFACT_BUCKET: /spotter/prod/artifact-bucket
phases:
  install:
    runtime-versions:
        python: 3.x
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/back/src/search_products
      - pip install --target package requests
      - pip install --target package requests_aws4auth
  build:
    commands:
      - sam build
      - sam package --s3-bucket ${ARTIFACT_BUCKET} --output-template-file ${CODEBUILD_SRC_DIR}/packaged-template.yml
    post_build:
      - rm -rf packages
artifacts:
  files:
    - packaged-template.yml
cache:
  paths:
    - '.venv/**/*'
