version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/back/src/search_products
  build:
    commands:
      - pip install --target package requests
      - pip install --target package requests_aws4auth
      - sam build
      - sam package --template-file template.yml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file ${CODEBUILD_SRC_DIR}/packaged-template.yml
      - rm -rf packages
artifacts:
  files:
    - packaged-template.yml
cache:
  paths:
    - '.venv/**/*'
