AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for building the


Resources:
  searchProductsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1

  searchProducts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      Timeout: 300
      MemorySize: 512
      CodeUri: .
      Layers:
        - !Ref SearchLayer
      Environment:
        Variables:
          MODE: production
      Events:
        SearchProducts:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref searchProductsApi

  SearchLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenSearch
      Description: Python Libraries for opensearch.
      ContentUri: package/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
