AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for building the


Resources:
  searchProductsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "spotter-front-docker"
          version: "1.0"
        servers:
          - url: "https://computer-store.dylanburris.me"
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
                passthroughBehavior: "when_no_match"
        components: { }
  searchProducts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      Timeout: 300
      MemorySize: 512
      CodeUri: .
      Layers:
        - !Ref SearchLayer
      Environment:
        Variables:
          MODE: production
      Events:
        SearchProducts:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref searchProductsApi

  SearchLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenSearch
      Description: Python Libraries for opensearch.
      ContentUri: package/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
