AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for building Computer Search.


Resources:
  SearchProducts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python3.9
      # AutoPublishAlias: live
      Timeout: 300
      MemorySize: 512
      CodeUri: .
      Layers:
        - !Ref SearchLayer
      Environment:
        Variables:
          MODE: production
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RequestParameters:
              - method.request.querystring.q:
                  Required: false
                  Caching: false


  SearchLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ProductSearch
      Description: Python Libraries for opensearch.
      ContentUri: .
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
