AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for building the


Resources:
  aliEngine:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      Timeout: 300
      MemorySize: 512
      CodeUri: src/
      Layers:
        - !Ref AliLayer
      Environment:
        Variables:
          MODE: production
  AliLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenSearch
      Description: Python Libraries for opensearch.
      ContentUri: package/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
