AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template for building the


Resources:
  searchProductsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "product-search"
          version: "2023-03-27T00:28:55Z"
        servers:
          - url: "https://skbf6e3i6f.execute-api.us-west-2.amazonaws.com/{basePath}"
            variables:
              basePath:
                default: "/v1"
        paths:
          /:
            get:
              parameters:
                - name: "q"
                  in: "query"
                  schema:
                    type: "string"
              responses:
                "200":
                  description: "200 response"
                  content:
                    application/json:
                      schema:
                        $ref: "#/components/schemas/Empty"
              x-amazon-apigateway-request-validator: "Validate query string parameters and\
                \ headers"
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                httpMethod: "POST"
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${searchProducts.Arn}/invocations
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"
        components:
          schemas:
            Empty:
              title: "Empty Schema"
              type: "object"
        x-amazon-apigateway-request-validators:
          Validate query string parameters and headers:
            validateRequestParameters: true
            validateRequestBody: false

  searchProducts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      Timeout: 300
      MemorySize: 512
      CodeUri: .
      Layers:
        - !Ref SearchLayer
      Environment:
        Variables:
          MODE: production
      Events:
        SearchProducts:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref searchProductsApi

  SearchLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenSearch
      Description: Python Libraries for opensearch.
      ContentUri: package/
      CompatibleRuntimes:
        - python3.9
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
