version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 16
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/front
  build:
    commands:
      - sam build
      - echo "IMAGE_URI ${IMAGE_URI}"
      - sam package --s3-bucket next-west-2.dylanburris.me --output-template-file ${CODEBUILD_SRC_DIR}/packaged-template.yml 072650510256.dkr.ecr.us-west-2.amazonaws.com/spotter-front-test
artifacts:
  files:
    - packaged-template.yml
cache:
  paths:
    - '.venv/**/*'
