version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 16
  pre_build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/front
  build:
    commands:
      - sam build
      - sam package --template-file template.yml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file ${CODEBUILD_SRC_DIR}/packaged-template.yml --image-repository ${IMAGE_URI}
artifacts:
  files:
    - packaged-template.yml
cache:
  paths:
    - '.venv/**/*'
