AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spotter Computer Store
  
Globals:
  Function:
    Timeout: 10

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
  NextjsImage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 512
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: get
            Path: /
            RestApiId:
              Ref: ApiGatewayApi
    Metadata:
      DockerTag: spotter-front-sam
      DockerContext: .
      Dockerfile: Dockerfile